services:
  interpretador:
    build: ./interpretador
    ports:
      - "5000:5000/udp"
      - "8080:8080/tcp"

  sensor_temp:
    build: ./sensor_temperatura
    depends_on: [interpretador]

  sensor_umid:
    build: ./sensor_umidade
    depends_on: [interpretador]

  atuador_ac:
    build: ./atuador_ac
    depends_on: [interpretador]

  irrigador:
    build: ./irrigador
    depends_on: [interpretador]

  cliente:
    build: ./cliente
    stdin_open: true
    tty: true
    depends_on: [interpretador]